#! /bin/bash
#SBATCH -p thin
#SBATCH -t 120:00:00
#SBATCH -n 1
#SBATCH --mail-user=l.florentie@vu.nl
#SBATCH --mail-type=FAIL,END

source ~/.bashrc_wrf

source activate daan

echo "Executing: srun run_ctdas_withrunner_cluster.py ../CTDAS_WRF_runs/testrun/settings_file_test_fwd_bigdomain.pkl --overwrite-ctdas=True  >& ./log/run_ctdas_withrunner_cluster.$SLURM_JOB_ID.log"

srun run_ctdas_withrunner_cluster.py ../CTDAS_WRF_runs/testrun/settings_file_test_fwd_bigdomain.pkl --overwrite-ctdas=True  >& ./log/run_ctdas_withrunner_cluster.$SLURM_JOB_ID.log
